In [1]:
from sklearn import datasets,linear_model
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

i=pd.read_csv('insu.csv')
# features=i['data']
# label=i['target']
i.head()


age  afford  insurance
0   12       0          0
1   55       1          1
2   78       1          0
3   90       0          0
4   47       1          1

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
x_train,x_test,y_train,y_test=train_test_split(i[['age','afford']],i.insurance,test_size=0.2,random_state=42)

In [4]:
x_train

age  afford
8    15       1
16   66       0
3    90       0
13   37       0
15   49       0
17   99       1
2    78       1
9    67       1
18   32       1
4    47       1
12   49       0
7    78       1
10   19       0
14   55       1
6    30       0

In [5]:
x_test



age  afford
0    12       0
5     2       0
11   18       1
1    55       1

In [6]:
# from tensorflow import keras
# model=keras.Sequential([
#     keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
    
# ])
# model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# model.fit(x_train,y_train,epochs=50)

In [7]:
x_scale=x_train.copy()
x_test1=x_test.copy()

In [8]:
x1=x_scale['age']/100
x11=x_scale['afford']/100
x2=x_test1['age']/100
x2

0     0.12
5     0.02
11    0.18
1     0.55
Name: age, dtype: float64

In [9]:
from tensorflow import keras
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
    
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_scale,y_train,epochs=50)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 18.1333 - accuracy: 0.6667
Epoch 2/50
1/1 [==============================] - 0s 8ms/step - loss: 18.1149 - accuracy: 0.6667
Epoch 3/50
1/1 [==============================] - 0s 19ms/step - loss: 18.0964 - accuracy: 0.6667
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 18.0779 - accuracy: 0.6667
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 18.0595 - accuracy: 0.6667
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 18.0410 - accuracy: 0.6667
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 18.0225 - accuracy: 0.6667
Epoch 8/50
1/1 [==============================] - 0s 8ms/step - loss: 18.0041 - accuracy: 0.6667
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 17.9856 - accuracy: 0.6667
Epoch 10/50
1/1 [==============================] - 0s 7ms/step - loss: 17.9671 - accuracy: 0.6667
Epoch 11/50
1/1 [============

In [10]:
# model.evaluate(x1,y_test)
model.predict(x_scale)


array([[0.99999976],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)

In [11]:
y_test

0     0
5     0
11    0
1     1
Name: insurance, dtype: int64

In [12]:
coef,intercept=model.get_weights()

In [13]:
coef,intercept

(array([[0.95000064],
        [0.95000064]], dtype=float32),
 array([-0.04999986], dtype=float32))

In [14]:
import math

def sigmoid(x):
    sig = 1 / (1 + math.exp(-x))
    return sig
# sigmoid(18)

In [15]:
def predition_function(age,afford):
#     intercept=1
    weighted_sum=coef[0]*age+coef[1]*afford+intercept
    return sigmoid(weighted_sum)


In [16]:
predition_function(47,1)

1.0

In [17]:
x1

8     0.15
16    0.66
3     0.90
13    0.37
15    0.49
17    0.99
2     0.78
9     0.67
18    0.32
4     0.47
12    0.49
7     0.78
10    0.19
14    0.55
6     0.30
Name: age, dtype: float64

In [18]:
x11

8     0.01
16    0.00
3     0.00
13    0.00
15    0.00
17    0.01
2     0.01
9     0.01
18    0.01
4     0.01
12    0.00
7     0.01
10    0.00
14    0.01
6     0.00
Name: afford, dtype: float64

In [19]:
y_train

8     0
16    1
3     0
13    1
15    1
17    1
2     0
9     0
18    1
4     1
12    1
7     1
10    0
14    1
6     1
Name: insurance, dtype: int64

In [20]:
def log_loss(y_true,y_predicted):
    e=1e-15
    y_pred_new=[max(i,e) for i in y_predicted]
    y_pred_new=[min(i,e) for i in y_pred_new]
    y_pred_new=np.array(y_pred_new)
    return  -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))


In [21]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))


array([0.99999386, 0.5       , 0.73105858])

In [23]:
class cm:
    def  __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0
    def fit(self,x,y,epochs,loss_thresold):
        self.w1,self.w2,self.bias=self.gradient(x['age'],x['afford'],y,epochs,loss_thresold)
    def predict(self,x_test):
        weighted_sum=self.w1*x_test['age']+self.w2*x_test['afford']+self.bias
        return sigmoid_numpy(weighted_sum)
    def gradient(self,age,afford,y_true,epochs,loss_thresold):
        w1=w2=1
        bias=0
        rate=0.5
        n=len(age)
        for i in range(epochs):
            weighted_sum=w1*age+w2*afford+bias
            y_predicted=sigmoid_numpy(weighted_sum)
            loss=log_loss(y_true,y_predicted)
            w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d=(1/n)*np.dot(np.transpose(afford),(y_predicted-y_true))
            bias_d=np.mean(y_predicted-y_true)
            w1=w1-rate*w1d
            w2=w2-rate*w2d
            bias=bias-rate*bias_d
            if i%50==0:
                print(f"epoch:{i},w1:{w1},w2:{w2},b:{bias},loss:{loss}")
            if loss<=loss_thresold:
                break
        return w1,w2,bias
    

        

In [24]:
# gradient(x_scale['age'],x_scale['afford'],y_train,1000, 17.2285)

In [25]:
# y_predicted

In [26]:
# (array([[0.95000064],
#         [0.95000064]], dtype=float32),
# #  array([-0.04999986], dtype=float32))

In [27]:
custommodel=cm()
custommodel.fit(x_scale,y_train,epochs=5,loss_thresold=17.2285 )

epoch:0,w1:-7.96666660685055,w2:0.9000000037511722,b:-0.16666666272873146,loss:23.025850929940454


c:\python3.9\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [28]:
custommodel.predict(x_scale)

8     1.0
16    1.0
3     1.0
13    1.0
15    1.0
17    1.0
2     1.0
9     1.0
18    1.0
4     1.0
12    1.0
7     1.0
10    1.0
14    1.0
6     1.0
dtype: float64

In [29]:
model.predict(x_scale)

array([[0.99999976],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)